This file is not scanned as there is no corresponding .py
We test this with a faulty test:

    >>> True
    False
